version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "ember",
    "meteor",
    "angular"
  ]
  environment = [
    "nodejs",
    "browser",
    "jquery",
    "mongo",
    "jest",
    "cypress",
    "vitest",
    "mocha",
    "jasmine"
  ]

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"